### PR TITLE
Change minimum color temperature constant to match LIFX Mini Day and Dusk specs

### PR DESCRIPTION
**Pull request by fkistner**
The LIFX Mini Day and Dusk supports color temperatures down to 1500 K.
This change updates the constant used for validation of the passed color temperatures.

This avoids validation errors when trying to set a temperature of 1500 K for Mini Day and Dusk bulb, such as: `LIFX light color method expects kelvin to be a number between 2500 and 9000 undefined`

### CODE REVIEW

**Comment by ristomatti** [comment]
Good catch. This would not fix the problem though as I now see the constants aren't haven't been used in validations in the packet modules for some reason. The value would need to be changed to all the appropriate places.

A hack approach would be to replace all `2500` values with the constant value but the validation would not be correct for most of the products. Proper solution would be to change the validation to be based on the light type and it's properties described in `products.json`. This would need to be done before sending any packets in the functions that change color.

To furher complicate this, if you would send a color value to all lights at once of which only some supported kelvin values below 2500, would it be better to just skip sending the value to lights that don't support it or should they be set to the closest supported value?

Value 2500 in the code (excluding `products.json`):
```
$ ag 2500 src
src/lifx/light.js
62: * @param {Number} [kelvin=3500]   color kelvin between 2500 and 9000
497: * @param {Number} [kelvin=3500] color kelvin between 2500 and 9000

src/lifx/validate.js
85:  const message = 'LIFX %s expects kelvin to be a number between 2500 and 9000';

src/lifx/packets/setColorZones.js
56: * @param  {Number} obj.color.kelvin between 2500 and 9000
99:  if (typeof obj.kelvin !== 'number' && obj.kelvin < 2500 || obj.kelvin > 9000) {
100:    throw new RangeError('Invalid color kelvin given for setColorZones LIFX packet, must be a number between 2500 and 9000');

src/lifx/packets/stateZone.js
50: * @param  {Number} obj.color.kelvin between 2500 and 9000
91:  if (typeof obj.kelvin !== 'number' && obj.kelvin < 2500 || obj.kelvin > 9000) {
92:    throw new RangeError('Invalid color kelvin given for stateZone LIFX packet, must be a number between 2500 and 9000');

src/lifx/packets/stateMultiZone.js
102:    if (typeof colorObj.kelvin !== 'number' && colorObj.kelvin < 2500 || colorObj.kelvin > 9000) {
103:      throw new RangeError('Invalid color kelvin given at index ' + index + ', must be a number between 2500 and 9000');

src/lifx/packets/setWaveform.js
61: * @param  {Number}  [obj.color.kelvin=3500] between 2500 and 9000
110:  if (typeof obj.color.kelvin !== 'number' && obj.color.kelvin < 2500 || obj.color.kelvin > 9000) {
111:    throw new RangeError('Invalid color kelvin given for setWaveform LIFX packet, must be a number between 2500 and 9000');

src/lifx/packets/setColor.js
48: * @param  {Number} obj.color.kelvin between 2500 and 9000
81:  if (typeof obj.kelvin !== 'number' && obj.kelvin < 2500 || obj.kelvin > 9000) {
82:    throw new RangeError('Invalid color kelvin given for setColor LIFX packet, must be a number between 2500 and 9000');

src/lifx.d.ts
153:  * @param {Number} [kelvin=3500]   color kelvin between 2500 and 9000
188:  * @param {Number} [kelvin=3500] color kelvin between 2500 and 9000
```

**Comment by ristomatti** [comment]
Mini Color's also support 1500K BTW. And curiously none of the Mini products support 3200K (on the app at least) like the older products did.

**Comment by fkistner** [comment]
Wow, that's an interesting one.

I can tell you I am able to set the color temperature on my Day and Dusk to 1500 K with these changes just fine. The problem I was running into were your changes to the validation logic in 00d2b1e931af58724232bd26521300bf1fd31032, which in fact use this constant:
```
src/lifx  (3 usages found)
    light.js  (2 usages found)
        69 validate.optionalKelvin(kelvin, 'light color method');
        507 validate.optionalKelvin(kelvin, 'color zones method');
    validate.js  (1 usage found)
        84 validate.optionalKelvin = function(kelvin, context) {
```

It would actually be interesting, if the validation is strictly necessary. How do bulbs respond when you send them a message with a color temperature beyond their capability? Do they just use the closest available color temperature? If that's the case, there's probably no point in investing time into coming up with a mechanism that takes into account the individual product information.

Anyways, why aren't there other validation errors when setting 1500 K, you might ask?
Well, it looks to me like the range checks you listed, in fact all the range checks in `src/lifx/packets` are broken :D

Consider, e.g.:
```diff
@@ -1 +1 @@
-typeof obj.hue !== 'number' && obj.hue < 0 || obj.hue > 65535
+typeof obj.hue !== 'number' || obj.hue < 0 || obj.hue > 65535

```

This is prevalent throughout:
```
src/lifx/packets  (32 usages found)
    getColorZones.js  (2 usages found)
        19 if (typeof obj.startIndex !== 'number' && obj.startIndex < 0 || obj.startIndex > 255) {
        25 if (typeof obj.endIndex !== 'number' && obj.endIndex < 0 || obj.endIndex > 255) {
    setColor.js  (4 usages found)
        60 if (typeof obj.hue !== 'number' && obj.hue < 0 || obj.hue > 65535) {
        66 if (typeof obj.saturation !== 'number' && obj.saturation < 0 || obj.saturation > 65535) {
        72 if (typeof obj.brightness !== 'number' && obj.brightness < 0 || obj.brightness > 65535) {
        81 if (typeof obj.kelvin !== 'number' && obj.kelvin < 2500 || obj.kelvin > 9000) {
    setColorZones.js  (4 usages found)
        66 if (typeof obj.startIndex !== 'number' && obj.startIndex < 0 || obj.startIndex > 255) {
        72 if (typeof obj.endIndex !== 'number' && obj.endIndex < 0 || obj.endIndex > 255) {
        99 if (typeof obj.kelvin !== 'number' && obj.kelvin < 2500 || obj.kelvin > 9000) {
        114 if (typeof obj.apply !== 'number' && obj.apply < 0 || obj.apply > 2) {
    setInfrared.js  (1 usage found)
        37 if (typeof obj.brightness !== 'number' && obj.brightness < 0 && obj.brightness > 65535) {
    setRgbw.js  (4 usages found)
        51 if (typeof obj.red !== 'number' && obj.red < 0 || obj.red > 65535) {
        60 if (typeof obj.green !== 'number' && obj.green < 0 || obj.green > 65535) {
        69 if (typeof obj.blue !== 'number' && obj.blue < 0 || obj.blue > 65535) {
        78 if (typeof obj.white !== 'number' && obj.white < 0 || obj.white > 65535) {
    setWaveform.js  (5 usages found)
        89 if (typeof obj.color.hue !== 'number' && obj.color.hue < 0 || obj.color.hue > 65535) {
        95 if (typeof obj.color.saturation !== 'number' && obj.color.saturation < 0 || obj.color.saturation > 65535) {
        101 if (typeof obj.color.brightness !== 'number' && obj.color.brightness < 0 || obj.color.brightness > 65535) {
        110 if (typeof obj.color.kelvin !== 'number' && obj.color.kelvin < 2500 || obj.color.kelvin > 9000) {
        146 if (typeof obj.waveform !== 'number' && obj.waveform < 0 || obj.waveform > (constants.LIGHT_WAVEFORMS.length - 1)) {
    stateMultiZone.js  (6 usages found)
        58 if (typeof obj.count !== 'number' && obj.count < 0 || obj.count > 255) {
        64 if (typeof obj.index !== 'number' && obj.index < 0 || obj.index > 255) {
        81 if (typeof colorObj.hue !== 'number' && colorObj.hue < 0 || colorObj.hue > 65535) {
        87 if (typeof colorObj.saturation !== 'number' && colorObj.saturation < 0 || colorObj.saturation > 65535) {
        93 if (typeof colorObj.brightness !== 'number' && colorObj.brightness < 0 || colorObj.brightness > 65535) {
        102 if (typeof colorObj.kelvin !== 'number' && colorObj.kelvin < 2500 || colorObj.kelvin > 9000) {
    stateZone.js  (6 usages found)
        58 if (typeof obj.count !== 'number' && obj.count < 0 || obj.count > 255) {
        64 if (typeof obj.index !== 'number' && obj.index < 0 || obj.index > 255) {
        70 if (typeof obj.hue !== 'number' && obj.hue < 0 || obj.hue > 65535) {
        76 if (typeof obj.saturation !== 'number' && obj.saturation < 0 || obj.saturation > 65535) {
        82 if (typeof obj.brightness !== 'number' && obj.brightness < 0 || obj.brightness > 65535) {
        91 if (typeof obj.kelvin !== 'number' && obj.kelvin < 2500 || obj.kelvin > 9000) {
```

**Comment by ristomatti** [comment]
Haha you are very correct that the validations are broken all around the packet code. And I'm guilty of copy pasting some of them also to those multizone packets. I've also been curious what was the intention with the packet level validation as the public API is already validated.

I'll try now what happens if I send 1500K to a LIFX original bulb.

**Comment by ristomatti** [comment]
Based on quick tests the original bulb changes to 2500K if set to 1500K. I don't like the solution as it is. It's not reflected on the documentation or JSDoc's. Not to mention those broken validations you just noticed...

But since I currently have no plans of officially forking this module and I know some people are using it even still for their home automation etc. projects, I think this is a good "undocumented" workaround for now. At least the library is not unnecessarily preventing people from setting values that are valid for their products.

Good findings overall! I have been so busy I hadn't even noticed the kelvin issue, even though I bought my Mini Color bulbs already some months ago.

Bonus obscure finding - like I earlier mentioned, LIFX app does not display 3200K in the color temperature for Mini Color bulbs like it does for LIFX Original bulbs. I was able to set it to 3200K through node-lifx and the color change was reflected. The light status even reported it's value to be 3200K afterwards. I wonder if they have calibrated certain values to actual kelvin values but the Mini series bulbs couldn't match 3200K correctly?

**Review by ristomatti — APPROVED** [review]

**Pull request merged**
